name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch (adjust if needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if you're using submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Or specify a specific Hugo version, e.g., '0.88.1'
          extended: true # Required if your theme uses SCSS/SASS

      - name: Build Site
        run: hugo --minify # Build the site and minify output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided, no need to create a secret
          publish_dir: ./public  # The directory Hugo outputs to (default: 'public')
          # cname: box3d.games # Uncomment this line and REMOVE the next if you DON'T have a custom domain
          external_repository: <your_github_username>/<your_github_username>.github.io
          publish_branch: main
          keep_files: false